Update Deploy.yml

diff --git a/.github/workflows/Deploy.yml b/.github/workflows/Deploy.yml
--- a/.github/workflows/Deploy.yml
+++ b/.github/workflows/Deploy.yml
@@ -135,6 +135,17 @@ jobs:
       - name: Get Code
         uses: actions/checkout@v3
 
+      - name: Run Tests
+        run: |
+            dotnet test TicketsManager.Tests/TicketsManager.Tests.csproj --logger "console;verbosity=normal"
+            if [ $? -ne 0 ]; then
+                echo "Tests failed, deployment canceled."
+                exit 1
+            else
+                echo "Tests passed, continuing with deployment."
+            fi
+        working-directory: ${{ env.PROJECT_PATH }}
+
       - name: Build and push image of User Manager
         id: build-n-push
         uses: ./.github/actions/Build-n-push
