Update deploy file (include auto start tests) and update test case for failed payment when

diff --git a/.github/workflows/Deploy.yml b/.github/workflows/Deploy.yml
--- a/.github/workflows/Deploy.yml
+++ b/.github/workflows/Deploy.yml
@@ -70,6 +70,17 @@ jobs:
     steps:
       - name: Get Code
         uses: actions/checkout@v4
+
+      - name: Run Tests
+        run: |
+            dotnet test PaymentManager.Tests/PaymentManager.Tests.csproj --logger "console;verbosity=normal"
+            if [ $? -ne 0 ]; then
+                echo "Tests failed, deployment canceled."
+                exit 1
+            else
+                echo "Tests passed, continuing with deployment."
+            fi
+        working-directory: ${{ env.PROJECT_PATH }}
       
       - name: Build and push image of PaymentManager
         id: build-n-push
